/*
 * TODO: TTM: rm
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'tmckinnon' at '3/10/15 6:10 PM' with Gradle 1.12
 *
 * @author tmckinnon, @date 3/10/15 6:10 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
