/*
 * TODO: TTM: rm
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'tmckinnon' at '3/10/15 6:10 PM' with Gradle 1.12
 *
 * @author tmckinnon, @date 3/10/15 6:10 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
